config/routes.rb
Rails.application.routes.draw do
  devise_for :agents, :controllers => { :registrations => 'agents/registrations' }

  devise_scope :agent do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    post '/agents', to: 'agents/registrations#create'
  end

  resources :agents, :controller => "agents", except: [:create]

  root to: 'static_pages#home'     
      
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about' 
  get 'contact' => 'static_pages#contact'
  get 'apps' => 'static_pages#apps'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
#  skip_authorization_check :only => [:home]
#  authorize_resource :class => false

  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def apps
    authorize! :apps, :static_page
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
    Rails and Devise, ready to rock and/or roll.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>rails-devise-template</h1>
  <h2>
    Rails and Devise, ready to go!
  </h2>
  <h3>Agent sign up</h3>
  <h3>Password resets</h3>
  <h3>SSH secure</h3>
  <h3>Tested</h3>
  <h2>Plus:</h2>
  <h3>Integrated React with Jest testing</h3>
  <h3>Capistrano ready</h3>
  <h3>PostgreSQL</h3>
  <h3>Figaro configurable</h3>
  <h3>Mobile friendly</h3>
  <h3>Nginx/Phusion Passenger</h3>
  <% if current_agent.nil? %>
    <%= link_to "Sign up now!", new_agent_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>