config/routes.rb
Rails.application.routes.draw do
  devise_for :agents, :controllers => { :registrations => 'agents/registrations' }

  devise_scope :agent do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    post '/agents', to: 'agents/registrations#create'
  end

  resources :agents, :controller => "agents", except: [:create]

  root to: 'static_pages#home'     
      
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about' 
  get 'contact' => 'static_pages#contact'
  get 'apps' => 'static_pages#apps'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Courtesy of 
    <a href="https://github.com/RaphaelDeLaGhetto/rails-devise-template">RaphaelDeLaGhetto</a>,
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to ENV['app_title'], root_path, id: "logo" %>
    </div> <!-- end div class="navbar-header" -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Help",   help_path %></li>
        <% if agent_signed_in? %>
          <li><%= link_to "Apps", apps_path %></li>
          <% if admin_logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" id="admin-dropdown" data-toggle="dropdown">Admin <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Agents", agents_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_agent %></li>
              <li><%= link_to "Settings", edit_agent_path(current_agent) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "get" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>      
    <%= render 'layouts/shim' %>
  </head>
  <body class="controller-<%= params[:controller] %>">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %> 
  </body>
</html>